DROP DATABASE IF EXISTS RoomFinder;
CREATE DATABASE RoomFinder;
USE RoomFinder;

#---------------------------------------------------------------------------------
CREATE TABLE BUILDING (
	BUILDING_ID INT NOT NULL AUTO_INCREMENT,
    BUILDING_NAME VARCHAR(255) NOT NULL,
    BUILDING_CITY VARCHAR(255) NOT NULL,
    BUILDING_ZIP VARCHAR(255) NOT NULL,
    BUILDING_STREET VARCHAR(255) NOT NULL,
    BUILDING_STATE VARCHAR(255) NOT NULL,
    CONSTRAINT BUILDING_PK PRIMARY KEY (BUILDING_ID)
);
INSERT INTO BUILDING VALUES(BUILDING_ID, "Thornton Hall", "Charlottesville", 22904, "351 McCormick Rd", "Virginia");
#---------------------------------------------------------------------------------
#MAY NEED COMPOSITE KEY LATER. PK = BUILDING NAME + ROOM NUM
CREATE TABLE ROOM (
	ROOM_ID INT NOT NULL AUTO_INCREMENT,
    BUILDING_ID INT NOT NULL,
    ROOM_NUMBER  VARCHAR(255) NOT NULL,
    CAPACITY INT NOT NULL,
    CONSTRAINT ROOM_PK PRIMARY KEY (ROOM_ID),
    CONSTRAINT ROOM_FK FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (BUILDING_ID)
);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'D223', 45);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'E304', 45);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'E316', 45);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'E303', 45);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'A120', 90);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'A006', 40);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'D222', 35);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'D008', 20);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'D115', 25);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'E225', 15);
INSERT INTO ROOM VALUES(ROOM_ID, 1, 'A238', 35);
#---------------------------------------------------------------------------------
#ROUND UP LOUS LIST DATA TO NEAREST HOUR
#ADD CONSTRAINT ON UNUSUAL TIME SLOTS.
#ASSUMPTION IS TIME BLOCKS ARE 1 HOUR INTERVALS FROM 1PM TO 4PM AND CAN ADD MORE LATER.
CREATE TABLE TIME_BLOCK (
	TIME_ID INT NOT NULL AUTO_INCREMENT,
    START_TIME VARCHAR(255),
    END_TIME VARCHAR(255),
    CONSTRAINT TIME_BLOCK_PK PRIMARY KEY (TIME_ID)
);
#TIME_ID 1 = 1-2PM, 2 = 2-3PM, 3 = 3-4PM.
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '8:00AM', '9:00AM'); #1
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '9:00AM', '10:00AM');#2
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '10:00AM', '11:00AM');#3
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '11:00AM', '12:00PM');#4
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '12:00PM', '1:00PM');#5
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '1:00PM', '2:00PM');#6
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '2:00PM', '3:00PM');#7
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '3:00PM', '4:00PM');#8
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '4:00PM', '5:00PM');#9
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '5:00PM', '6:00PM');#10
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '6:00PM', '7:00PM');#11
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '7:00PM', '8:00PM');#12
INSERT INTO TIME_BLOCK VALUES(TIME_ID, '8:00PM', '9:00PM');#13
#---------------------------------------------------------------------------------
CREATE TABLE AVAILABILITY (
	AVAILABILITY_ID INT NOT NULL AUTO_INCREMENT,
	ROOM_ID INT NOT NULL,
    AVAILABLE_DAY VARCHAR(255) NOT NULL,
    TIME_ID INT NOT NULL,
    #NeedS a primary key SO MADE IT ROOM_ID SINCE ALL ROOMS HAVE A UNIQUE ID EVEN IF THEIR ROOM_NUM IS THE SAME SO AVAILABILITY WILL ASSOCIATE W/ EACH ROOM_ID
    CONSTRAINT AVAILABILITY_PK PRIMARY KEY (AVAILABILITY_ID),
    CONSTRAINT AVAILABILITY_FK1 FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID),
    CONSTRAINT AVAILABILITY_FK2 FOREIGN KEY (TIME_ID) REFERENCES TIME_BLOCK(TIME_ID)
    #CONSTRAINT AVAILABILITY_FK3 FOREIGN KEY (AVAILABLE_DAY) REFERENCES #UNSURE WHAT ENTITY THIS FK REFERENCES FROM THE ERD
);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'MONDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'MONDAY', 13);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'TUESDAY', 13); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'WEDNESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'WEDNESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'WEDNESDAY', 13); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'THURSDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'THURSDAY', 13);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 1, 'FRIDAY', 13); 
#E304 (2)
#------------------------------------------------------------------------------------------
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'MONDAY', 1); #room id for E304 on monday, with corresponding time block
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'MONDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'MONDAY', 10); #room id for E304 on monday, with corresponding time block
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'MONDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'MONDAY', 12); #room id for E304 on monday, with corresponding time block
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'MONDAY', 13); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'TUESDAY', 13); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'WEDNESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'WEDNESDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'WEDNESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'WEDNESDAY', 13); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'THURSDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'THURSDAY', 13);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 2, 'FRIDAY', 13); 
#---------------------------------------------------------------------------------
#E316 (3)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'MONDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'MONDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'TUESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'TUESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'TUESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'WEDNESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'WEDNESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'WEDNESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'THURSDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 3, 'FRIDAY', 13);
#-------------------------------------------------------------------------
#E303 (4)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'MONDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'MONDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'TUESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'TUESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'WEDNESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'WEDNESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'WEDNESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'THURSDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'THURSDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 4, 'FRIDAY', 13);
#------------------------------------------------------------------------
#A120 (5)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'TUESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'WEDNESDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'WEDNESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'WEDNESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'THURSDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 5, 'FRIDAY', 13);
#----------------------------------------------------------------------------
#A006 (6)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 2);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 4);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 7);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 8);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 9);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'TUESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'WEDNESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 2);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 4);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 6, 'FRIDAY', 13);
#-----------------------------------------------------------------------------------
#D222 (7)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'TUESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'TUESDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'TUESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'WEDNESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'WEDNESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'THURSDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 7, 'FRIDAY', 13);
#----------------------------------------------------------------------------
#D008 (8)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 2);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 4);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 7);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 8);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 9);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'TUESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 9);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'WEDNESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 8, 'FRIDAY', 13);
#--------------------------------------------------------------------------------
#D115 (9)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'MONDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'MONDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'MONDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'TUESDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'TUESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'WEDNESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'WEDNESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'THURSDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'FRIDAY', 5);  
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 9, 'FRIDAY', 13);
#--------------------------------------------------------------------
#E225 (10)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 2);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 3);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 4);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 7);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 8);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 9);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'TUESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 9);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'WEDNESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 7);  
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 8);  
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 4);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 8);  
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 10, 'FRIDAY', 13);
#----------------------------------------------------------
#A238 (11)
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'MONDAY', 9);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'MONDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'MONDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'MONDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'MONDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'TUESDAY', 6); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'TUESDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'TUESDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'TUESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'TUESDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 1);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 5);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 9);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'WEDNESDAY', 13); 

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'THURSDAY', 10);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'THURSDAY', 11);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'THURSDAY', 12);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'THURSDAY', 13);

INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 1); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 2); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 3); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 4); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 5); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 6);
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 7); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 8); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 9); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 10); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 11); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 12); 
INSERT INTO AVAILABILITY VALUES(AVAILABILITY_ID, 11, 'FRIDAY', 13);
#---------------------------------------------------------------------------------
 CREATE TABLE STUDENT (
	STUDENT_ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_FNAME VARCHAR(255) NOT NULL,
    STUDENT_LNAME VARCHAR(255) NOT NULL,
    STUDENT_EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT STUDENT_PK PRIMARY KEY (STUDENT_ID)
 );
 INSERT INTO STUDENT VALUES(STUDENT_ID, 'ALEX', 'D', 'ALEX@VIRGINIA.EDU');
 INSERT INTO STUDENT VALUES(STUDENT_ID, 'RAMEN', 'S', 'RAMEN@VIRGINIA.EDU');
 INSERT INTO STUDENT VALUES(STUDENT_ID, 'SOFIA', 'A', 'SOFIA@VIRGINIA.EDU');
 INSERT INTO STUDENT VALUES(STUDENT_ID, 'ERIC', 'W', 'ERIC@VIRGINIA.EDU');
  #---------------------------------------------------------------------------------
#SPLITS THE M:N RELATIONSHIP BETWEEN ROOM AND STUDENT
 CREATE TABLE STUDENT_ROOM (
    STUDENT_ID INT NOT NULL AUTO_INCREMENT,
    ROOM_ID INT NOT NULL,
    CONSTRAINT STUDENT_ROOM_PK PRIMARY KEY (STUDENT_ID, ROOM_ID), #COMPOSITE PRIMARY KEY OF STUDENT_ID ASSIGNED TO ROOM_ID
    CONSTRAINT STUDENT_ROOM_FK1 FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID),
    CONSTRAINT STUDENT_ROOM_FK2 FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID)
 );
#STUDENT ID: 1 = ALEX, 2 = RAMEN, 3 = SOFIA, 4 = ERIC
INSERT INTO STUDENT_ROOM VALUES(1, 3); 
INSERT INTO STUDENT_ROOM VALUES(2, 5);
INSERT INTO STUDENT_ROOM VALUES(3, 7); 
INSERT INTO STUDENT_ROOM VALUES(4, 10);
#---------------------------------------------------------------------------------
 CREATE TABLE RESERVATION (
	RESERVATION_ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    RESERVATION_DATE VARCHAR(255),
    TIME_ID INT NOT NULL,
    CONSTRAINT RESERVATION_PK PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT RESERVATION_FK1 FOREIGN KEY (TIME_ID) REFERENCES TIME_BLOCK(TIME_ID),
	CONSTRAINT RESERVATION_FK2 FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID)
 ); 
#STUDENT ID: 1 = ALEX, 2 = RAMEN, 3 = SOFIA, 4 = ERIC
INSERT INTO RESERVATION VALUES(RESERVATION_ID, 1, 3, 'Monday', 1); #ALEX RESERVES RICE HALL 032 ON 6/18/2022 FROM 1-2PM
INSERT INTO RESERVATION VALUES(RESERVATION_ID, 2, 5, 'Thursday', 10); #RAMEN RESERVES RICE HALL 032 ON 6/22/2022 FROM 3-4PM
INSERT INTO RESERVATION VALUES(RESERVATION_ID, 3, 7, 'Wednesday', 12); #SOFIA RESERVES OLSSON HALL 005 ON 6/14/2022 FROM 3-4PM
INSERT INTO RESERVATION VALUES(RESERVATION_ID, 4, 10, 'Monday', 8); #ERIC RESERVES OLSSON HALL 120 ON 6/18/2022 FROM 2-3PMSTUDENT_FNAME

SELECT *
FROM BUILDING;
SELECT *
FROM ROOM;
SELECT *
FROM AVAILABILITY;
SELECT *
FROM TIME_BLOCK;
SELECT * 
FROM RESERVATION;
SELECT *
FROM STUDENT;
SELECT *
FROM STUDENT_ROOM;