# Generated by Django 4.0.5 on 2022-06-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(db_column='BUILDING_ID', primary_key=True, serialize=False)),
                ('building_name', models.CharField(db_column='BUILDING_NAME', max_length=255)),
                ('building_city', models.CharField(db_column='BUILDING_CITY', max_length=255)),
                ('building_zip', models.CharField(db_column='BUILDING_ZIP', max_length=255)),
                ('building_street', models.CharField(db_column='BUILDING_STREET', max_length=255)),
                ('building_state', models.CharField(db_column='BUILDING_STATE', max_length=255)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(db_column='STUDENT_ID', primary_key=True, serialize=False)),
                ('student_fname', models.CharField(db_column='STUDENT_FNAME', max_length=255)),
                ('student_lname', models.CharField(db_column='STUDENT_LNAME', max_length=255)),
                ('student_email', models.CharField(db_column='STUDENT_EMAIL', max_length=255)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('time_id', models.AutoField(db_column='TIME_ID', primary_key=True, serialize=False)),
                ('start_time', models.CharField(blank=True, db_column='START_TIME', max_length=255, null=True)),
                ('end_time', models.CharField(blank=True, db_column='END_TIME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'time_block',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='ROOM_ID', primary_key=True, serialize=False)),
                ('room_number', models.CharField(db_column='ROOM_NUMBER', max_length=255)),
                ('capacity', models.IntegerField(db_column='CAPACITY')),
                ('building', models.ForeignKey(db_column='BUILDING_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.building')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(db_column='RESERVATION_ID', primary_key=True, serialize=False)),
                ('room_id', models.IntegerField(db_column='ROOM_ID')),
                ('reservation_date', models.CharField(blank=True, db_column='RESERVATION_DATE', max_length=255, null=True)),
                ('student', models.ForeignKey(db_column='STUDENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.student')),
                ('time_id', models.ForeignKey(db_column='TIME_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.timeblock')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(db_column='RATING_ID', primary_key=True, serialize=False)),
                ('rating_score', models.IntegerField(db_column='RATING_SCORE')),
                ('room', models.ForeignKey(db_column='ROOM_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.room')),
                ('student', models.ForeignKey(db_column='STUDENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.student')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(db_column='AVAILABILITY_ID', primary_key=True, serialize=False)),
                ('available_day', models.CharField(db_column='AVAILABLE_DAY', max_length=255)),
                ('room', models.ForeignKey(db_column='ROOM_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.room')),
                ('time', models.ForeignKey(db_column='TIME_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.timeblock')),
            ],
            options={
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='StudentRoom',
            fields=[
                ('student', models.OneToOneField(db_column='STUDENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='finder.student')),
                ('room', models.ForeignKey(db_column='ROOM_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='finder.room')),
            ],
            options={
                'db_table': 'student_room',
                'unique_together': {('student', 'room')},
            },
        ),
    ]
