# Generated by Django 4.0.2 on 2022-06-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUILDING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUILDING_NAME', models.CharField(max_length=255)),
                ('BUILDING_CITY', models.CharField(max_length=255)),
                ('BUILDING_ZIP', models.CharField(max_length=255)),
                ('BUILDING_STREET', models.CharField(max_length=255)),
                ('BUILDING_STATE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ROOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOM_NUMBER', models.CharField(max_length=255)),
                ('CAPACITY', models.IntegerField()),
                ('BUILDING_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.building')),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT_FNAME', models.CharField(max_length=255)),
                ('STUDENT_LNAME', models.CharField(max_length=255)),
                ('STUDENT_EMAIL', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT_ROOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.room')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.student')),
            ],
        ),
    ]
